#!/usr/bin/env python

import rpi_abb_irc5
import time
import math
import numpy as np

def main():
    try:
        egm=rpi_abb_irc5.EGM()

        while True:
            res, state=egm.receive_from_robot(.01)
            angle=np.deg2rad(10*math.sin(time.time()))
            if res:
                print "Joints: " + str(state.joint_angles)
                joint_angles=[angle]*6
                egm.send_to_robot(joint_angles)
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    main()
