#!/usr/bin/env python

import rpi_abb_irc5
import time
import math
import numpy as np

def main():
    try:
        egm=rpi_abb_irc5.EGM()
        t1=time.time()
        while True:
            res, state=egm.receive_from_robot(.01)
            angle=np.deg2rad(60*((time.time()-t1)/10))
            if res:
                print "ID: " + str(state.robot_message.header.seqno) + " Joints: " + str(np.rad2deg(state.joint_angles))
                joint_angles=[angle]*6
                egm.send_to_robot(state.joint_angles)
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    main()
